// src/Shimmer.tsx
import React, { useLayoutEffect, useState, useRef } from 'react';
import { ShimmerProps, ElementInfo } from './types';
import { useShimmerConfig } from './ShimmerContext';

/**
 * Check if an element is a "leaf" content element that should be rendered as shimmer
 */
function isLeafElement(element: Element): boolean {
  const tag = element.tagName.toLowerCase();

  // Always include these elements as they're always content
  const alwaysInclude = ['img', 'svg', 'video', 'canvas', 'iframe', 'input', 'textarea', 'button'];
  if (alwaysInclude.includes(tag)) {
    return true;
  }

  // Check if element has no element children (only text nodes or no children)
  const hasElementChildren = Array.from(element.children).length > 0;
  if (!hasElementChildren) {
    // This is a leaf element (contains only text or is empty)
    return true;
  }

  return false;
}

/**
 * Extracts dimension information from content-bearing elements in a DOM tree
 */
function extractElementInfo(element: Element, parentRect: DOMRect): ElementInfo[] {
  const elements: ElementInfo[] = [];
  const rect = element.getBoundingClientRect();

  // Skip elements with no dimensions
  if (rect.width === 0 || rect.height === 0) {
    return elements;
  }

  // If this is a leaf element, capture it
  if (isLeafElement(element)) {
    // Get computed border-radius from the element's styles
    const computedStyle = window.getComputedStyle(element);
    const computedBorderRadius = computedStyle.borderRadius || '0px';

    const info: ElementInfo = {
      x: rect.left - parentRect.left,
      y: rect.top - parentRect.top,
      width: rect.width,
      height: rect.height,
      tag: element.tagName.toLowerCase(),
      borderRadius: computedBorderRadius,
    };
    elements.push(info);
  } else {
    // Otherwise, recursively process children
    Array.from(element.children).forEach((child) => {
      elements.push(...extractElementInfo(child, parentRect));
    });
  }

  return elements;
}

/**
 * Shimmer component that adapts to the actual rendered structure of its children
 */
export const Shimmer: React.FC<ShimmerProps> = ({
  children,
  loading = true,
  shimmerColor,
  backgroundColor,
  duration,
  fallbackBorderRadius,
  templateProps,
}) => {
  // Get context values (contains defaults if no provider)
  const contextConfig = useShimmerConfig();

  // Merge: props > context > defaults
  const resolvedShimmerColor = shimmerColor ?? contextConfig.shimmerColor;
  const resolvedBackgroundColor = backgroundColor ?? contextConfig.backgroundColor;
  const resolvedDuration = duration ?? contextConfig.duration;
  const resolvedFallbackBorderRadius = fallbackBorderRadius ?? contextConfig.fallbackBorderRadius;

  const [elements, setElements] = useState<ElementInfo[]>([]);
  const contentRef = useRef<HTMLDivElement>(null);
  const measureRef = useRef<HTMLDivElement>(null);

  // Prepare children with injected template props when loading
  const childrenToRender = React.useMemo(() => {
    // Only inject template props if loading and templateProps is provided
    if (!loading || !templateProps) {
      return children;
    }

    // Get the first child
    const childArray = React.Children.toArray(children);
    if (childArray.length === 0) {
      return children;
    }

    const firstChild = childArray[0];

    // Check if it's a valid React element that can receive props
    if (!React.isValidElement(firstChild)) {
      return children;
    }

    // Clone the first child with the template props spread onto it
    const clonedChild = React.cloneElement(firstChild, {
      ...templateProps,
    });

    // Return cloned first child + rest of children unchanged
    return [clonedChild, ...childArray.slice(1)];
  }, [children, loading, templateProps]);

  // Measure the structure using useLayoutEffect (synchronous, before paint)
  useLayoutEffect(() => {
    if (!loading || !measureRef.current) return;

    const container = measureRef.current;
    const containerRect = container.getBoundingClientRect();

    // Extract all element dimensions
    const extractedElements: ElementInfo[] = [];
    Array.from(container.children).forEach((child) => {
      extractedElements.push(...extractElementInfo(child, containerRect));
    });

    setElements(extractedElements);
  }, [loading, childrenToRender]);

  if (!loading) {
    return <>{children}</>;
  }

  return (
    <div style={{ position: 'relative' }}>
      {/* Inject styles for hiding text while preserving backgrounds */}
      <style>{`
        .shimmer-measure-container * {
          color: transparent !important;
          border-color: transparent !important;
        }
        .shimmer-measure-container img,
        .shimmer-measure-container svg,
        .shimmer-measure-container video {
          opacity: 0;
        }
      `}</style>

      {/* Children rendered with transparent text but visible container backgrounds */}
      <div
        ref={measureRef}
        className="shimmer-measure-container"
        style={{
          pointerEvents: 'none',
        }}
        aria-hidden="true"
      >
        {childrenToRender}
      </div>

      {/* Shimmer overlay based on measured dimensions */}
      <div
        ref={contentRef}
        style={{
          position: 'absolute',
          top: 0,
          left: 0,
          right: 0,
          bottom: 0,
          overflow: 'hidden',
        }}
      >
        <style>{`
          @keyframes shimmer {
            0% {
              transform: translateX(-100%);
            }
            100% {
              transform: translateX(100%);
            }
          }
        `}</style>

        {elements.map((element, index) => (
          <div
            key={index}
            style={{
              position: 'absolute',
              left: `${element.x}px`,
              top: `${element.y}px`,
              width: `${element.width}px`,
              height: `${element.height}px`,
              backgroundColor: resolvedBackgroundColor,
              borderRadius: element.borderRadius === '0px'
                ? `${resolvedFallbackBorderRadius}px`
                : element.borderRadius,
              overflow: 'hidden',
            }}
          >
            <div
              style={{
                position: 'absolute',
                top: 0,
                left: 0,
                width: '100%',
                height: '100%',
                background: `linear-gradient(90deg, transparent, ${resolvedShimmerColor}, transparent)`,
                animation: `shimmer ${resolvedDuration}s infinite`,
              }}
            />
          </div>
        ))}
      </div>
    </div >
  );
};

// packages/svelte/src/Shimmer.svelte
<script lang="ts">
  import { onMount, tick } from 'svelte';
  import { extractElementInfo, type ElementInfo } from '@shimmer-from-structure/core';
  import { getShimmerConfig } from './ShimmerContext';

  export let loading: boolean = true;
  export let shimmerColor: string | undefined = undefined;
  export let backgroundColor: string | undefined = undefined;
  export let duration: number | undefined = undefined;
  export let fallbackBorderRadius: number | undefined = undefined;
  export let templateProps: Record<string, any> | undefined = undefined;

  let measureRef: HTMLDivElement;
  let elements: ElementInfo[] = [];

  const contextConfig = getShimmerConfig();

  $: resolvedShimmerColor = shimmerColor ?? contextConfig.shimmerColor;
  $: resolvedBackgroundColor = backgroundColor ?? contextConfig.backgroundColor;
  $: resolvedDuration = duration ?? contextConfig.duration;
  $: resolvedFallbackBorderRadius = fallbackBorderRadius ?? contextConfig.fallbackBorderRadius;

  async function measureElements() {
    if (!loading || !measureRef) return;

    // Temporarily stop observing to avoid recursion from DOM-modifying measurements
    // (e.g. extractElementInfo temporarily wrapping text in spans)
    observer?.disconnect();

    // Wait for DOM update
    await tick();

    const container = measureRef;
    const containerRect = container.getBoundingClientRect();
    const extractedElements: ElementInfo[] = [];

    Array.from(container.children).forEach((child) => {
      extractedElements.push(...extractElementInfo(child, containerRect));
    });

    elements = extractedElements;

    // Restart observation session
    if (measureRef && observer) {
      observer.observe(measureRef, {
        childList: true,
        subtree: true,
        characterData: true,
        attributes: false,
      });
    }
  }

  // Re-measure when loading state changes
  $: if (loading && measureRef) {
    measureElements();
  }

  let observer: MutationObserver | undefined;

  onMount(() => {
    measureElements();

    if (measureRef) {
      observer = new MutationObserver(() => {
        // Only observe changes in the measure container (slot content changes)
        // Don't trigger when we're not loading
        if (loading) {
          measureElements();
        }
      });

      // Only observe the slot content changes, NOT the shimmer overlay
      observer.observe(measureRef, {
        childList: true,
        subtree: true,
        characterData: true,
        attributes: false, // Don't observe attribute changes (style updates)
      });
    }

    return () => {
      observer?.disconnect();
    };
  });

  // Helper to signal content change from parent (optional)
  export function remeasure() {
    measureElements();
  }
</script>

{#if !loading}
  <slot></slot>
{:else}
  <div style="position: relative;">
    <!-- Measure container with transparent text -->
    <div
      bind:this={measureRef}
      class="shimmer-measure-container"
      style="pointer-events: none;"
      aria-hidden="true"
    >
      {#if templateProps}
        <!-- Slot with template props injected via context -->
        <slot shimmerTemplateProps={templateProps}></slot>
      {:else}
        <slot></slot>
      {/if}
    </div>

    <!-- Shimmer overlay - isolated from mutation observer -->
    <div
      style="
        position: absolute;
        top: 0;
        left: 0;
        right: 0;
        bottom: 0;
        overflow: hidden;
        pointer-events: none;
      "
    >
      {#each elements as element, index (index)}
        <div
          style="
            position: absolute;
            left: {element.x}px;
            top: {element.y}px;
            width: {element.width}px;
            height: {element.height}px;
            background-color: {resolvedBackgroundColor};
            border-radius: {element.borderRadius === '0px'
            ? resolvedFallbackBorderRadius + 'px'
            : element.borderRadius};
            overflow: hidden;
          "
        >
          <div
            style="
              position: absolute;
              top: 0;
              left: 0;
              width: 100%;
              height: 100%;
              background: linear-gradient(90deg, transparent, {resolvedShimmerColor}, transparent);
              animation: shimmer-animation {resolvedDuration}s infinite;
            "
          ></div>
        </div>
      {/each}
    </div>
  </div>
{/if}

<style>
  .shimmer-measure-container :global(*) {
    color: transparent !important;
  }
  .shimmer-measure-container :global(img),
  .shimmer-measure-container :global(svg),
  .shimmer-measure-container :global(video) {
    opacity: 0;
  }
  @keyframes shimmer-animation {
    0% {
      transform: translateX(-100%);
    }
    100% {
      transform: translateX(100%);
    }
  }
</style>
